const proyectos = [
  {
    nombre: "Bitescreadoresdesonrisas.com",
    categoria: "Dentistas",
    img: "/portafolio.webp",
    url: "https://bitescreadoresdesonrisas.com",
    description: "Descripción del proyecto Bitescreadoresdesonrisas.com",
    old: true,
    oldImage: "/projects/bites.webp",
  },
  {
    nombre: "Reformadental.com",
    categoria: "Dentistas",
    img: "/portafolio.webp",
    url: "https://reformadental.com",
    description: "Descripción del proyecto Reformadental.com",
    old: true,
    oldImage: "/projects/reforma.webp",
  },
  {
    nombre: "dentalreforma",
    categoria: "Dentistas",
    img: "/portafolio.webp",
    url: "https://dentalreforma.com",
    description: "Descripción del proyecto dentalreforma",
    old: true,
    oldImage: "/old-dentalreforma.webp",
  },
  {
    nombre: "Mongeortopedia.com",
    categoria: "Médicos",
    img: "/portafolio.webp",
    url: "https://mongeortopedia.com",
    description: "Descripción del proyecto Mongeortopedia.com",
    old: true,
    oldImage: "/projects/monge.webp",
  },
  {
    nombre: "Cesiaborjon.com",
    categoria: "Médicos",
    img: "/portafolio.webp",
    url: "https://cesiaborjon.com",
    description: "Descripción del proyecto Cesiaborjon.com",
    old: true,
    oldImage: "/old-cesiaborjon.webp",
  },
  {
    nombre: "Doctorarturlopez.com",
    categoria: "Médicos",
    img: "/portafolio.webp",
    url: "https://doctorarturlopez.com",
    description: "Descripción del proyecto Doctorarturlopez.com",
    old: true,
    oldImage: "/old-doctorarturlopez.webp",
  },
  {
    nombre: "doctorapamelaperez.com",
    categoria: "Médicos",
    img: "/portafolio.webp",
    url: "https://doctorapamelaperez.com",
    description: "Descripción del proyecto doctorapamelaperez.com",
    old: true,
    oldImage: "/old-doctorapamelaperez.webp",
  },
  {
    nombre: "Carboneticsinc.com",
    categoria: "Industria",
    img: "/portafolio.webp",
    url: "https://carboneticsinc.com",
    description: "Descripción del proyecto Carboneticsinc.com",
    old: true,
    oldImage: "/old-carboneticsinc.webp",
  },
  {
    nombre: "Lacocina.mx",
    categoria: "Industria",
    img: "/portafolio.webp",
    url: "https://lacocina.mx",
    description: "Descripción del proyecto Lacocina.mx",
    old: true,
    oldImage: "/old-lacocina.webp",
  },
  {
    nombre: "Wislinfarm.com",
    categoria: "Industria",
    img: "/portafolio.webp",
    url: "https://wislinfarm.com",
    description: "Descripción del proyecto Wislinfarm.com",
    old: true,
    oldImage: "/projects/wislin.webp",
  },
  {
    nombre: "Sylindustrial.com",
    categoria: "Industria",
    img: "/portafolio.webp",
    url: "https://sylindustrial.com/",
    description: "Descripción del proyecto Sylindustrial.com",
    old: true,
    oldImage: "/old-sylsuinistros.webp",
  },
  {
    nombre: "e-commetrics.com",
    categoria: "Industria",
    img: "/portafolio.webp",
    url: "https://e-commetrics.com",
    description: "Descripción del proyecto e-commetrics.com",
    old: true,
    oldImage: "/old-e-commetrics.webp",
  },
  {
    nombre: "kamili.com",
    categoria: "Industria",
    img: "/portafolio.webp",
    url: "https://kamili.com",
    description: "Descripción del proyecto kamili.com",
    old: true,
    oldImage: "/old-kamili.webp",
  },
  {
    nombre: "gpeconsultores.com.mx",
    categoria: "Consultorías",
    img: "/portafolio.webp",
    url: "https://gpeconsultores.com.mx",
    description: "Descripción del proyecto gpeconsultores.com.mx",
    old: true,
    oldImage: "/projects/gpe.webp",
  },
  {
    nombre: "syltalento.com",
    categoria: "Consultorías",
    img: "/portafolio.webp",
    url: "https://syltalento.com",
    description: "Descripción del proyecto syltalento.com",
    old: true,
    oldImage: "/old-syltalento.webp",
  },
  {
    nombre: "bordergrower.com",
    categoria: "Comercializadoras",
    img: "/portafolio.webp",
    url: "https://bordergrower.com",
    description: "Descripción del proyecto bordergrower.com",
    old: true,
    oldImage: "/old-bordergrower.webp",
  },
  {
    nombre: "Chik.mx",
    categoria: "Comercializadoras",
    img: "/portafolio.webp",
    url: "https://chik.mx",
    description: "Descripción del proyecto Chik.mx",
    old: true,
    oldImage: "/old-chik.webp",
  },
  {
    nombre: "labodegasolar.com",
    categoria: "Comercializadoras",
    img: "/portafolio.webp",
    url: "https://labodegasolar.com",
    description: "Descripción del proyecto labodegasolar.com",
    old: true,
    oldImage: "/old-labodegasolar.webp",
  },
  {
    nombre: "ziggiz.world",
    categoria: "Comercializadoras",
    img: "/portafolio.webp",
    url: "https://ziggiz.world",
    description: "Descripción del proyecto ziggiz.world",
    old: true,
    oldImage: "/projects/ziggiz.png",
  },
  {
    nombre: "proyectotijuana-claudionaranjo.com",
    categoria: "Otros",
    img: "/portafolio.webp",
    url: "https://proyectotijuana-claudionaranjo.com",
    description: "Descripción del proyecto proyectotijuana-claudionaranjo.com",
    old: true,
    oldImage: "/old-proyectotijuana-claudionaranjo.webp",
  },
  {
    nombre: "tallerursuablanco.com",
    categoria: "Otros",
    img: "/portafolio.webp",
    url: "https://tallerursuablanco.com",
    description: "Descripción del proyecto tallerursuablanco.com",
    old: true,
    oldImage: "/old-tallerursuablanco.webp",
  },
  {
    nombre: "ignaciozaragoza3.com",
    categoria: "Otros",
    img: "/portafolio.webp",
    url: "https://ignaciozaragoza3.com",
    description: "Descripción del proyecto ignaciozaragoza3.com",
    old: true,
    oldImage: "/old-ignaciozaragoza.webp",
  },
];

export default proyectos;
